#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update

spring:
 jpa:
   properties:
      javax:
       persistence:
        validation:
         mode: none
   
 main:
  allow-bean-definition-overriding: true
         
logging:
  level:
    '[org.springframework]': debug
    
   
